/* eslint-disable linebreak-style */
import Head from 'next/head'
import Inspect from 'inspx'
import NavBar from '../components/Navbar/NavBar'
import Layout from '../components/Layout/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Easings saver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Inspect>
        <NavBar />
        <Layout />
      </Inspect>
    </>
  )
}
