import Head from 'next/head'
import { NavBar, Layout } from '../components'
import Inspect from 'inspx';

export default function Home() {
  return (
    <>
      <Head>
        <title>Easings saver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Inspect>
        <NavBar />
        <Layout />
      </Inspect>
    </>
  )
}
  